"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class HistoryItem(google.protobuf.message.Message):
    """Conversation messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROLE_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    role: builtins.str
    """"user" | "bot" """
    text: builtins.str
    def __init__(
        self,
        *,
        role: builtins.str = ...,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["role", b"role", "text", b"text"]) -> None: ...

global___HistoryItem = HistoryItem

@typing.final
class Start(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["request_id", b"request_id"]) -> None: ...

global___Start = Start

@typing.final
class UserText(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXT_FIELD_NUMBER: builtins.int
    text: builtins.str
    def __init__(
        self,
        *,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["text", b"text"]) -> None: ...

global___UserText = UserText

@typing.final
class BotText(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXT_FIELD_NUMBER: builtins.int
    text: builtins.str
    def __init__(
        self,
        *,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["text", b"text"]) -> None: ...

global___BotText = BotText

@typing.final
class BotAudio(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PCM16_FIELD_NUMBER: builtins.int
    pcm16: builtins.bytes
    """16 kHz, 16-bit PCM mono frames"""
    def __init__(
        self,
        *,
        pcm16: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pcm16", b"pcm16"]) -> None: ...

global___BotAudio = BotAudio

@typing.final
class Done(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Done = Done

@typing.final
class Error(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___Error = Error

@typing.final
class SpeakingRequest(google.protobuf.message.Message):
    """Speaking (server-streaming)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOPIC_FIELD_NUMBER: builtins.int
    USER_AUDIO_URL_FIELD_NUMBER: builtins.int
    HISTORY_LOG_FIELD_NUMBER: builtins.int
    ACCENT_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    MESSAGE_ID_FIELD_NUMBER: builtins.int
    topic: builtins.str
    """e.g., "General" """
    user_audio_url: builtins.str
    """empty string => first turn (no audio)"""
    accent: builtins.str
    """e.g., "american" """
    gender: builtins.str
    """e.g., "feminine" """
    speed: builtins.float
    """e.g., 1.0"""
    session_id: builtins.str
    """session ID for backend notification"""
    message_id: builtins.str
    """message ID for backend notification"""
    @property
    def history_log(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HistoryItem]:
        """role-based chat history"""

    def __init__(
        self,
        *,
        topic: builtins.str = ...,
        user_audio_url: builtins.str = ...,
        history_log: collections.abc.Iterable[global___HistoryItem] | None = ...,
        accent: builtins.str = ...,
        gender: builtins.str = ...,
        speed: builtins.float = ...,
        session_id: builtins.str = ...,
        message_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accent", b"accent", "gender", b"gender", "history_log", b"history_log", "message_id", b"message_id", "session_id", b"session_id", "speed", b"speed", "topic", b"topic", "user_audio_url", b"user_audio_url"]) -> None: ...

global___SpeakingRequest = SpeakingRequest

@typing.final
class SpeakingEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    USER_TEXT_FIELD_NUMBER: builtins.int
    BOT_TEXT_FIELD_NUMBER: builtins.int
    BOT_AUDIO_FIELD_NUMBER: builtins.int
    DONE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def start(self) -> global___Start: ...
    @property
    def user_text(self) -> global___UserText:
        """transcript back to client"""

    @property
    def bot_text(self) -> global___BotText:
        """model reply text"""

    @property
    def bot_audio(self) -> global___BotAudio:
        """PCM16 chunks"""

    @property
    def done(self) -> global___Done: ...
    @property
    def error(self) -> global___Error: ...
    def __init__(
        self,
        *,
        start: global___Start | None = ...,
        user_text: global___UserText | None = ...,
        bot_text: global___BotText | None = ...,
        bot_audio: global___BotAudio | None = ...,
        done: global___Done | None = ...,
        error: global___Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["bot_audio", b"bot_audio", "bot_text", b"bot_text", "done", b"done", "error", b"error", "event", b"event", "start", b"start", "user_text", b"user_text"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bot_audio", b"bot_audio", "bot_text", b"bot_text", "done", b"done", "error", b"error", "event", b"event", "start", b"start", "user_text", b"user_text"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["event", b"event"]) -> typing.Literal["start", "user_text", "bot_text", "bot_audio", "done", "error"] | None: ...

global___SpeakingEvent = SpeakingEvent

@typing.final
class TopicValidationRequest(google.protobuf.message.Message):
    """Topic validation"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOPIC_NAME_FIELD_NUMBER: builtins.int
    topic_name: builtins.str
    def __init__(
        self,
        *,
        topic_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["topic_name", b"topic_name"]) -> None: ...

global___TopicValidationRequest = TopicValidationRequest

@typing.final
class TopicValidationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALIDATION_FIELD_NUMBER: builtins.int
    validation: builtins.str
    """"BROAD" | "NARROW" """
    def __init__(
        self,
        *,
        validation: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["validation", b"validation"]) -> None: ...

global___TopicValidationResponse = TopicValidationResponse

@typing.final
class TranslateRequest(google.protobuf.message.Message):
    """Translation"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXT_FIELD_NUMBER: builtins.int
    text: builtins.str
    """source text"""
    def __init__(
        self,
        *,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["text", b"text"]) -> None: ...

global___TranslateRequest = TranslateRequest

@typing.final
class TranslateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSLATED_TEXT_FIELD_NUMBER: builtins.int
    translated_text: builtins.str
    def __init__(
        self,
        *,
        translated_text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["translated_text", b"translated_text"]) -> None: ...

global___TranslateResponse = TranslateResponse

@typing.final
class HintRequest(google.protobuf.message.Message):
    """Hint"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESPONSE_TEXT_FIELD_NUMBER: builtins.int
    response_text: builtins.str
    """the bot's response for which to generate hint(s)"""
    def __init__(
        self,
        *,
        response_text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["response_text", b"response_text"]) -> None: ...

global___HintRequest = HintRequest

@typing.final
class HintResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HINT_FIELD_NUMBER: builtins.int
    hint: builtins.str
    def __init__(
        self,
        *,
        hint: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["hint", b"hint"]) -> None: ...

global___HintResponse = HintResponse

@typing.final
class TryByYourselfRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASPECT_FIELD_NUMBER: builtins.int
    USER_AUDIO_URL_FIELD_NUMBER: builtins.int
    aspect: builtins.str
    """e.g., "grammar", "vocabulary", "pronunciation", "fluency" """
    user_audio_url: builtins.str
    def __init__(
        self,
        *,
        aspect: builtins.str = ...,
        user_audio_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["aspect", b"aspect", "user_audio_url", b"user_audio_url"]) -> None: ...

global___TryByYourselfRequest = TryByYourselfRequest

@typing.final
class TryByYourselfResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCORE_FIELD_NUMBER: builtins.int
    score: builtins.int
    def __init__(
        self,
        *,
        score: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["score", b"score"]) -> None: ...

global___TryByYourselfResponse = TryByYourselfResponse
