"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class EvaluateGrammarResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    MESSAGE_ID_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    CORRECTED_TRANSCRIPT_FIELD_NUMBER: builtins.int
    EXPLANATION_FIELD_NUMBER: builtins.int
    TENSE_USED_FIELD_NUMBER: builtins.int
    CORRECTED_AUDIO_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    message_id: builtins.str
    score: builtins.float
    corrected_transcript: builtins.str
    explanation: builtins.str
    tense_used: builtins.str
    corrected_audio: builtins.bytes
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        message_id: builtins.str = ...,
        score: builtins.float = ...,
        corrected_transcript: builtins.str = ...,
        explanation: builtins.str = ...,
        tense_used: builtins.str = ...,
        corrected_audio: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["corrected_audio", b"corrected_audio", "corrected_transcript", b"corrected_transcript", "explanation", b"explanation", "message_id", b"message_id", "score", b"score", "session_id", b"session_id", "tense_used", b"tense_used"]) -> None: ...

global___EvaluateGrammarResponse = EvaluateGrammarResponse

@typing.final
class VocabularyEntry(google.protobuf.message.Message):
    """Per-token synonym entry"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORD_FIELD_NUMBER: builtins.int
    CEFR_FIELD_NUMBER: builtins.int
    PRONUNCIATION_FIELD_NUMBER: builtins.int
    DEFINITION_FIELD_NUMBER: builtins.int
    EXAMPLE_SENTENCE_TRANSCRIPT_FIELD_NUMBER: builtins.int
    EXAMPLE_SENTENCE_AUDIO_FIELD_NUMBER: builtins.int
    word: builtins.str
    cefr: builtins.str
    """e.g., "A1" | "B1" | "NA" """
    pronunciation: builtins.str
    definition: builtins.str
    example_sentence_transcript: builtins.str
    example_sentence_audio: builtins.bytes
    def __init__(
        self,
        *,
        word: builtins.str = ...,
        cefr: builtins.str = ...,
        pronunciation: builtins.str = ...,
        definition: builtins.str = ...,
        example_sentence_transcript: builtins.str = ...,
        example_sentence_audio: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cefr", b"cefr", "definition", b"definition", "example_sentence_audio", b"example_sentence_audio", "example_sentence_transcript", b"example_sentence_transcript", "pronunciation", b"pronunciation", "word", b"word"]) -> None: ...

global___VocabularyEntry = VocabularyEntry

@typing.final
class VocabularyToken(google.protobuf.message.Message):
    """Vocabulary token with optional synonyms"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORIGINAL_FIELD_NUMBER: builtins.int
    SYNONYMS_FIELD_NUMBER: builtins.int
    @property
    def original(self) -> global___VocabularyEntry: ...
    @property
    def synonyms(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VocabularyEntry]:
        """optional; can be empty"""

    def __init__(
        self,
        *,
        original: global___VocabularyEntry | None = ...,
        synonyms: collections.abc.Iterable[global___VocabularyEntry] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["original", b"original"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["original", b"original", "synonyms", b"synonyms"]) -> None: ...

global___VocabularyToken = VocabularyToken

@typing.final
class EvaluateVocabularyResponse(google.protobuf.message.Message):
    """Aggregated vocabulary evaluation"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class StatisticsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    SESSION_ID_FIELD_NUMBER: builtins.int
    MESSAGE_ID_FIELD_NUMBER: builtins.int
    STATISTICS_FIELD_NUMBER: builtins.int
    TOKENS_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    message_id: builtins.str
    @property
    def statistics(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.int]:
        """CEFR counts, e.g., {"A1":3,"A2":0,"B1":0,"B2":0,"C1":0,"C2":0}"""

    @property
    def tokens(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VocabularyToken]:
        """Detailed per-token analysis"""

    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        message_id: builtins.str = ...,
        statistics: collections.abc.Mapping[builtins.str, builtins.int] | None = ...,
        tokens: collections.abc.Iterable[global___VocabularyToken] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message_id", b"message_id", "session_id", b"session_id", "statistics", b"statistics", "tokens", b"tokens"]) -> None: ...

global___EvaluateVocabularyResponse = EvaluateVocabularyResponse

@typing.final
class PronunciationToken(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCORE_FIELD_NUMBER: builtins.int
    WORD_FIELD_NUMBER: builtins.int
    WRONG_TRANSCRIPT_FIELD_NUMBER: builtins.int
    CORRECTED_TRANSCRIPT_FIELD_NUMBER: builtins.int
    CORRECTED_IPA_FIELD_NUMBER: builtins.int
    CORRECTED_AUDIO_FIELD_NUMBER: builtins.int
    score: builtins.int
    """0-100"""
    word: builtins.str
    wrong_transcript: builtins.str
    """all fields below is available if score < 1.0"""
    corrected_transcript: builtins.str
    corrected_ipa: builtins.str
    corrected_audio: builtins.bytes
    def __init__(
        self,
        *,
        score: builtins.int = ...,
        word: builtins.str = ...,
        wrong_transcript: builtins.str = ...,
        corrected_transcript: builtins.str = ...,
        corrected_ipa: builtins.str = ...,
        corrected_audio: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["corrected_audio", b"corrected_audio", "corrected_ipa", b"corrected_ipa", "corrected_transcript", b"corrected_transcript", "score", b"score", "word", b"word", "wrong_transcript", b"wrong_transcript"]) -> None: ...

global___PronunciationToken = PronunciationToken

@typing.final
class EvaluatePronunciationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    MESSAGE_ID_FIELD_NUMBER: builtins.int
    OVERALL_SCORE_FIELD_NUMBER: builtins.int
    TOKENS_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    message_id: builtins.str
    overall_score: builtins.int
    @property
    def tokens(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PronunciationToken]: ...
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        message_id: builtins.str = ...,
        overall_score: builtins.int = ...,
        tokens: collections.abc.Iterable[global___PronunciationToken] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message_id", b"message_id", "overall_score", b"overall_score", "session_id", b"session_id", "tokens", b"tokens"]) -> None: ...

global___EvaluatePronunciationResponse = EvaluatePronunciationResponse
