# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\nai_service\")\n\x0bHistoryItem\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x1b\n\x05Start\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"#\n\x0eUserTranscript\x12\x11\n\tuser_text\x18\x01 \x01(\t\"\x1f\n\x0b\x42otResponse\x12\x10\n\x08\x62ot_text\x18\x01 \x01(\t\"\x19\n\x08TTSChunk\x12\r\n\x05pcm16\x18\x01 \x01(\x0c\"\x06\n\x04\x44one\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x95\x01\n\x0fSpeakingRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x16\n\x0euser_audio_url\x18\x02 \x01(\t\x12,\n\x0bhistory_log\x18\x03 \x03(\x0b\x32\x17.ai_service.HistoryItem\x12\x0e\n\x06\x61\x63\x63\x65nt\x18\x04 \x01(\t\x12\x0e\n\x06gender\x18\x05 \x01(\t\x12\r\n\x05speed\x18\x06 \x01(\x02\"\x81\x02\n\rSpeakingEvent\x12\"\n\x05start\x18\x01 \x01(\x0b\x32\x11.ai_service.StartH\x00\x12\x30\n\ntranscript\x18\x02 \x01(\x0b\x32\x1a.ai_service.UserTranscriptH\x00\x12&\n\x03\x62ot\x18\x03 \x01(\x0b\x32\x17.ai_service.BotResponseH\x00\x12#\n\x03tts\x18\x04 \x01(\x0b\x32\x14.ai_service.TTSChunkH\x00\x12 \n\x04\x64one\x18\x05 \x01(\x0b\x32\x10.ai_service.DoneH\x00\x12\"\n\x05\x65rror\x18\x06 \x01(\x0b\x32\x11.ai_service.ErrorH\x00\x42\x07\n\x05\x65vent2X\n\tAiService\x12K\n\x0fProcessSpeaking\x12\x1b.ai_service.SpeakingRequest\x1a\x19.ai_service.SpeakingEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HISTORYITEM']._serialized_start=32
  _globals['_HISTORYITEM']._serialized_end=73
  _globals['_START']._serialized_start=75
  _globals['_START']._serialized_end=102
  _globals['_USERTRANSCRIPT']._serialized_start=104
  _globals['_USERTRANSCRIPT']._serialized_end=139
  _globals['_BOTRESPONSE']._serialized_start=141
  _globals['_BOTRESPONSE']._serialized_end=172
  _globals['_TTSCHUNK']._serialized_start=174
  _globals['_TTSCHUNK']._serialized_end=199
  _globals['_DONE']._serialized_start=201
  _globals['_DONE']._serialized_end=207
  _globals['_ERROR']._serialized_start=209
  _globals['_ERROR']._serialized_end=233
  _globals['_SPEAKINGREQUEST']._serialized_start=236
  _globals['_SPEAKINGREQUEST']._serialized_end=385
  _globals['_SPEAKINGEVENT']._serialized_start=388
  _globals['_SPEAKINGEVENT']._serialized_end=645
  _globals['_AISERVICE']._serialized_start=647
  _globals['_AISERVICE']._serialized_end=735
# @@protoc_insertion_point(module_scope)
