# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessSpeaking = channel.unary_stream(
                '/ai_service.AiService/ProcessSpeaking',
                request_serializer=ai__service__pb2.SpeakingRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SpeakingEvent.FromString,
                _registered_method=True)
        self.ValidateTopic = channel.unary_unary(
                '/ai_service.AiService/ValidateTopic',
                request_serializer=ai__service__pb2.TopicValidationRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TopicValidationResponse.FromString,
                _registered_method=True)
        self.TranslateText = channel.unary_unary(
                '/ai_service.AiService/TranslateText',
                request_serializer=ai__service__pb2.TranslateRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TranslateResponse.FromString,
                _registered_method=True)
        self.GenerateHint = channel.unary_unary(
                '/ai_service.AiService/GenerateHint',
                request_serializer=ai__service__pb2.HintRequest.SerializeToString,
                response_deserializer=ai__service__pb2.HintResponse.FromString,
                _registered_method=True)
        self.EvaluateGrammar = channel.unary_unary(
                '/ai_service.AiService/EvaluateGrammar',
                request_serializer=ai__service__pb2.EvaluateGrammarRequest.SerializeToString,
                response_deserializer=ai__service__pb2.EvaluateGrammarResponse.FromString,
                _registered_method=True)


class AiServiceServicer(object):
    """Service
    """

    def ProcessSpeaking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateTopic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranslateText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateHint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateGrammar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessSpeaking': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessSpeaking,
                    request_deserializer=ai__service__pb2.SpeakingRequest.FromString,
                    response_serializer=ai__service__pb2.SpeakingEvent.SerializeToString,
            ),
            'ValidateTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateTopic,
                    request_deserializer=ai__service__pb2.TopicValidationRequest.FromString,
                    response_serializer=ai__service__pb2.TopicValidationResponse.SerializeToString,
            ),
            'TranslateText': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateText,
                    request_deserializer=ai__service__pb2.TranslateRequest.FromString,
                    response_serializer=ai__service__pb2.TranslateResponse.SerializeToString,
            ),
            'GenerateHint': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateHint,
                    request_deserializer=ai__service__pb2.HintRequest.FromString,
                    response_serializer=ai__service__pb2.HintResponse.SerializeToString,
            ),
            'EvaluateGrammar': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateGrammar,
                    request_deserializer=ai__service__pb2.EvaluateGrammarRequest.FromString,
                    response_serializer=ai__service__pb2.EvaluateGrammarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_service.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_service.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService(object):
    """Service
    """

    @staticmethod
    def ProcessSpeaking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_service.AiService/ProcessSpeaking',
            ai__service__pb2.SpeakingRequest.SerializeToString,
            ai__service__pb2.SpeakingEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/ValidateTopic',
            ai__service__pb2.TopicValidationRequest.SerializeToString,
            ai__service__pb2.TopicValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranslateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/TranslateText',
            ai__service__pb2.TranslateRequest.SerializeToString,
            ai__service__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateHint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/GenerateHint',
            ai__service__pb2.HintRequest.SerializeToString,
            ai__service__pb2.HintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateGrammar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/EvaluateGrammar',
            ai__service__pb2.EvaluateGrammarRequest.SerializeToString,
            ai__service__pb2.EvaluateGrammarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
